cc_binary(
    name = "oko",
    srcs = [
        "log_file.h",
        "log_record.h",
        "log_view.h",
        "main.cc",
        "memorylog_log_file.cc",
        "memorylog_log_file.h",
    ],
    deps = [
        "@boost//:iostreams",
        "@boost//:program_options",
        "@libcxx",
    ],
)
